################################################################################
# Add x, y, z coordinates and radial distance to table of domains
# Mac, R/3.6.1
################################################################################
# FLAGS * FLAGS * FLAGS * FLAGS * FLAGS * FLAGS * FLAGS * FLAGS * FLAGS * FLAGS
### DIRECTORY STRUCTURE ########################################################
whorunsit = "LiezelMac" # "LiezelMac", "LiezelCluster", "LiezelLinuxDesk",
# "AlexMac", "AlexCluster"

if( !is.null(whorunsit[1]) ){
  # This can be expanded as needed ...
  if(whorunsit == "LiezelMac"){
    lib = "/Users/ltamon/DPhil/lib"
    wk.dir = "/Users/ltamon/DPhil/GenomicContactDynamics/6_Chrom3D"
    cmm.dir = "/Users/ltamon/DPhil/Chrom3D/H1-hESC/result"
    os = "Mac"
  } else {
    print("The supplied <whorunsit> option is not created in the script.", quote=FALSE)
  }
}

model.id = "IMR90_LMNB1_GSE49341_hg19" # "IMR90_LMNB1_GSE49341_hg19" | "H1-hESC_LMNB1_hg38"
cmm.dir = paste0(wk.dir, "/0_cmm/", model.id)
gtrack.dir = paste0(wk.dir, "/0_gtrack/", model.id)
out.dir = paste0(wk.dir, "/out_AddXYZR")
### OTHER SETTINGS #############################################################
ploidy.v = c("haploid")
# Instead of the gtrackfile, RData object generated by DomainVsFeature can also
# be used
domRobj = FALSE
# Column with chr info
dom.chr = "###seqid"
# Column with beadID (used to match with cmm file)
dom.id = "id"
################################################################################
# LIBRARIES & DEPENDANCES * LIBRARIES & DEPENDANCIES * LIBRARIES & DEPENDANCES *
################################################################################
library(compiler)
library(data.table)
source(paste0(lib, "/getcmmXYZradi.R"))
source(paste0(lib, "/getCOM.R"))
source(paste0(lib, "/getRadDist.R"))
source(paste0(lib, "/loadRData.R"))
### FUNCTION ###################################################################
AddXYZR <- function(
  out.dir = paste0(wk.dir, "/out_Chrom3D"),
  # cmm file generated by Chrom3D contains xyz coordinates
  cmmfile = paste0(cmm.dir, "/IMR90_inter_intra_chr_w_LADs_diploid.cmm"),
  # Should correspond with cmmfile.v
  ploidy = "diploid", # "haploid"
  model.id = "IMR90",
  # Load model setup file (.gtrack) with domain coordinates
  # Also contains information on interaction
  domainfile = "/Users/ltamon/DPhil/Chrom3D/IMR90/IMR90_inter_intra_chr_w_LADs.gtrack",
  # Instead of the gtrackfile, RData object generated by DomainVsFeature can also
  # be used
  domRobj = FALSE,
  # Column with chr info
  dom.chr = "###seqid",
  # Column with beadID (used to match with cmm file)
  dom.id = "id"
){
  
  # Load domain file
  if(domRobj==FALSE){
    DOMAIN.df <- fread(file=domainfile, header=TRUE, data.table=FALSE,
                       stringsAsFactors=FALSE)
  } else {
    DOMAIN.df <- loadRData(file=domainfile)
  }
  
  # Change colname of chr 
  setnames(x=DOMAIN.df, old=dom.chr, new="chr")
  
  #---------------------------------------
  # Add x,y,z coordinates from cmm file to table of domains
  cmmXYZradi <- getcmmXYZR(cmmPath=cmmfile)
  # chr column already in the domain file
  cmmXYZradi$chr <- NULL
  
  # Make sure domain ids match between domain and cmm files
  if( !setequal( unique(DOMAIN.df$id), unique(cmmXYZradi$id)) |
      length(unique(DOMAIN.df$id))!=length(unique(cmmXYZradi$id)) ){
    stop("Inconsistent beadIDs.")
  }
  
  # Merge based on bead ID
  DOMAIN.df <- merge(x=DOMAIN.df, y=cmmXYZradi, by="id", all.x=TRUE)
  rm(cmmXYZradi)
  
  #---------------------------
  # Calculate center of mass to calculate radial distance per domain
  com <- getCOM(weight=DOMAIN.df$cmmRadius,
                coordinates=DOMAIN.df[,c("x","y","z")])
  radDist <- apply(DOMAIN.df[,c("x","y","z")], MARGIN=1, 
                  FUN=function(xyz){
                    getRadDist(xyz1=com, xyz2=xyz)
                  })
  DOMXYZR.DF <- cbind.data.frame(radDist=radDist, DOMAIN.df,
                                 stringsAsFactors=FALSE)
 
  
  # Check if all domains are present in DOMXYZR.DF
  if(!all(DOMAIN.df$id%in%DOMXYZR.DF$id)){
    stop("Checkpoint")
  }
  
  rm(radDist, DOMAIN.df); gc()
  
  save(DOMXYZR.DF, file=paste0(out.dir, "/", model.id, "_", ploidy, 
                               "_domXYZR.RData"))
  
}
################################################################################
AddXYZR <- cmpfun(AddXYZR, options=list(suppressUndefined=TRUE))
################################################################################
# MAIN CODE * MAIN CODE * MAIN CODE * MAIN CODE * MAIN CODE * MAIN CODE *
################################################################################
for(ploidy in ploidy.v){
  
  cmmfile <- paste0(cmm.dir, "/", list.files(cmm.dir, pattern=ploidy,
                                             include.dirs=FALSE, recursive=TRUE))
  domainfile <- paste0(gtrack.dir, "/", list.files(gtrack.dir, pattern=ploidy, 
                                                   include.dirs=FALSE, recursive=TRUE))
 
  AddXYZR(
    out.dir=out.dir,
    # cmm file generated by Chrom3D contains xyz coordinates
    cmmfile=cmmfile,
    # Should correspond with cmmfile.v
    ploidy=ploidy, # "diploid"
    model.id=model.id,
    # Load model setup file (.gtrack) with domain coordinates
    # Also contains information on interaction
    domainfile=domainfile,
    # Instead of the gtrackfile, RData object generated by DomainVsFeature can also
    # be used
    domRobj=domRobj ,
    # Column with chr info
    dom.chr=dom.chr,
    # Column with beadID (used to match with cmm file)
    dom.id=dom.id
  )
    
} # cmmfile.v.len for loop end 

# rm(list=ls())
